# -*- coding: utf-8 -*-
"""baseadmin

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XvFan8b2oaS1Iz-OvAyjvC834aioxnB9
"""

from sqlalchemy import create_engine
from procesamientodatos import data_tabla, data_tabla2, data_tabla3

engine = create_engine('postgresql://postgres:admin123@localhost:5432/datos')

data_tabla.to_sql('tabla_unica', con=engine, if_exists='replace')
data_tabla2.to_sql('tabla_cines', con=engine, if_exists='replace')
data_tabla3.to_sql('tabla_categorias_fuentes', con=engine, if_exists='replace')

